export const PRICES = {
    CRICKET_COURT_WITH_BALLING_MACHINE : 1300,
    CRICKET_COURT_WITHOUT_BALLING_MACHINE : 1000,
    BADMINTON_COURT : 750,
    FINE:200,
    GYM_ACTIVATION_FEE: 1500,
    SCHOOL_MEMBERSHIP_PRICE:1500
}